import { ArrowLeft, Download, Printer } from 'lucide-react';
import { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useStore } from '../../contexts/StoreContext';
import { formatMoney } from '../../lib/utils';

export default function Invoice() {
  const { id }=useParams();
  const { orders,settings,loadAdmin,adminLoaded }=useStore();
  useEffect(()=>{if(!adminLoaded)loadAdmin().catch(()=>{});},[adminLoaded,loadAdmin]);
  const order=orders.find(item=>item.id===id);
  if(!order)return <div className="screen-loader">Loading invoice...</div>;
  return <div className="invoice-page"><div className="invoice-actions no-print"><Link className="btn btn-light" to="/admin/orders"><ArrowLeft size={16}/>Back</Link><button className="btn btn-primary" onClick={()=>window.print()}><Printer size={16}/>Print / Save PDF</button></div><article className="invoice-sheet"><header><div className="invoice-brand"><span className="brand-mark">S</span><div><h1>{settings?.storeName}</h1><p>{settings?.address}</p><p>{settings?.supportPhone} · {settings?.supportEmail}</p></div></div><div className="invoice-title"><span>INVOICE</span><strong>{order.orderNumber}</strong><small>{new Date(order.createdAt).toLocaleDateString()}</small></div></header><section className="invoice-meta"><div><small>BILL TO</small><h3>{order.customer?.name}</h3><p>{order.customer?.phone}</p><p>{order.customer?.email}</p><p>{order.customer?.address}</p></div><div><small>ORDER DETAILS</small><p><span>Status</span><strong>{order.status}</strong></p><p><span>Payment</span><strong>{order.paymentMethodName}</strong></p><p><span>Payment Status</span><strong>{order.paymentStatus}</strong></p><p><span>Shipping Area</span><strong>{order.shippingAreaName}</strong></p></div></section><table className="invoice-table"><thead><tr><th>Item</th><th>Options</th><th>Qty</th><th>Unit</th><th>Total</th></tr></thead><tbody>{order.items?.map(item=><tr key={item.id||item.sku}><td><div className="invoice-product"><img src={item.image} alt=""/><span><strong>{item.name}</strong><small>{item.sku}</small></span></div></td><td>{Object.entries(item.selectedOptionLabels||{}).map(([label,value])=><div key={label}><strong>{label}:</strong> {value}</div>)}</td><td>{item.quantity}</td><td>{formatMoney(item.unitPrice,settings?.currencySymbol)}</td><td>{formatMoney(item.unitPrice*item.quantity,settings?.currencySymbol)}</td></tr>)}</tbody></table><section className="invoice-totals"><div><span>Subtotal</span><strong>{formatMoney(order.subtotal,settings?.currencySymbol)}</strong></div><div><span>Shipping</span><strong>{formatMoney(order.shippingFee,settings?.currencySymbol)}</strong></div>{order.discount>0&&<div><span>Discount {order.couponCode&&`(${order.couponCode})`}</span><strong>-{formatMoney(order.discount,settings?.currencySymbol)}</strong></div>}<div className="grand-total"><span>Grand Total</span><strong>{formatMoney(order.total,settings?.currencySymbol)}</strong></div></section><footer><p>{settings?.invoiceNote||'Thank you for shopping with us.'}</p><small>{settings?.footerText}</small></footer></article></div>;
}
