import { ExternalLink, FileText, Search } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useStore } from '../../contexts/StoreContext';
import { formatMoney } from '../../lib/utils';

export default function Orders() {
  const { orders,settings,loadAdmin,adminLoaded,updateOrder }=useStore();
  const[query,setQuery]=useState(''); const[status,setStatus]=useState('');
  useEffect(()=>{if(!adminLoaded)loadAdmin().catch(()=>{});},[adminLoaded,loadAdmin]);
  const rows=useMemo(()=>orders.filter(order=>`${order.orderNumber} ${order.customer?.name} ${order.customer?.phone}`.toLowerCase().includes(query.toLowerCase())&&(!status||order.status===status)),[orders,query,status]);
  const change=async(order,key,value)=>{await updateOrder(order.id,{[key]:value});};
  return <div><div className="admin-page-heading"><div><span className="eyebrow">Fulfilment</span><h1>Orders</h1><p>Manage status and print smart invoices.</p></div></div><div className="admin-toolbar"><label className="search-field"><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Order number, name or phone..."/></label><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">All status</option><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="processing">Processing</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div><section className="admin-panel table-panel"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Order Status</th><th>Payment</th><th>Shipping</th><th>Invoice</th></tr></thead><tbody>{rows.map(order=><tr key={order.id}><td><strong>{order.orderNumber}</strong><small>{new Date(order.createdAt).toLocaleString()}</small></td><td><strong>{order.customer?.name}</strong><small>{order.customer?.phone}</small></td><td>{formatMoney(order.total,settings?.currencySymbol)}</td><td><select value={order.status} onChange={event=>change(order,'status',event.target.value)}><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="processing">Processing</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="refunded">Refunded</option></select></td><td><select value={order.paymentStatus} onChange={event=>change(order,'paymentStatus',event.target.value)}><option value="unpaid">Unpaid</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select></td><td><select value={order.shippingStatus} onChange={event=>change(order,'shippingStatus',event.target.value)}><option value="unfulfilled">Unfulfilled</option><option value="processing">Processing</option><option value="packed">Packed</option><option value="shipped">Shipped</option><option value="in_transit">In Transit</option><option value="delivered">Delivered</option><option value="returned">Returned</option></select></td><td><Link className="btn btn-primary btn-small" to={`/admin/orders/${order.id}/invoice`}><FileText size={15}/>Invoice</Link></td></tr>)}</tbody></table></div></section></div>;
}
